name: argos_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.2.1

  image_picker: ^1.2.1
  camera: ^0.12.0+1

  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.2.0
  webview_flutter: ^4.13.1
  cloud_functions: ^6.2.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/argos_icon.png"
  adaptive_icon_background: "#0057C0"
  adaptive_icon_foreground: "assets/icon/argos_icon.png"
  min_sdk_android: 21